name: E2E Tests

on:
  push:
    branches: [master, main]

env:
  CI: true
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm t
